# Generated by Django 5.2.1 on 2025-05-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='posts.post'),
        ),
    ]
