# Generated by Django 5.2.1 on 2025-05-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_content_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('blue', 'Blue'), ('orange', 'Orange'), ('gray', 'Gray'), ('white', 'White')], default='white', max_length=10),
        ),
    ]
